language: node_js
node_js:
  - "6"
git:
  depth: 3
branches:
  only:
    - master
before_install: cd functions
before_script:
  - cd $TRAVIS_BUILD_DIR
  - npm install -g firebase-tools
script: 
  - scripts/set-firebase-env.sh
  - firebase deploy --token=$FIREBASE_TOKEN --non-interactive
cache:
  directories:
    - $(npm config get prefix)/bin/firebase-tools
    - functions/node_modules