language: node_js
node_js:
  - "6"
git:
  depth: 3
before_script:
  - npm install -g firebase-tools
script: scripts/set-firebase-env.sh
deploy:
  - provider: firebase
    token: $FIREBASE_TOKEN
    on:
      branch: master
cache:
  directories:
    - $(npm config get prefix)/bin/firebase-tools